name: new code
on: push

jobs:
   test:
     steps:
       -name: Runa a one line script 
          run: echo "hello world"
#Directly run a command
       -name: list all files in the directory
         directory:
           run: ls -la
       -name: checkout code
          uses: actions/checout@v6.0.2
       -name: list all files in the directory
        repository:
          run: ls -al




